import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Plus_Jakarta_Sans, Commissioner } from 'next/font/google'
import { IBM_Plex_Sans } from "next/font/google";


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});
const plusJakartaSans = Plus_Jakarta_Sans({
  variable: "--font-plus-jakarta-sans",
  subsets: ["latin"],
  weight: ['600'],
});
const commissionerExtraBold = Commissioner({
  variable: "--font-commissioner-bold",
  subsets: ["latin"],
  weight: ['400'],
});

const ibmPlexSans = IBM_Plex_Sans({
  variable: "--font-ibm-plex-sans",
  subsets: ["latin"],
  weight: ['400'],
});

export const metadata: Metadata = {
  title: "trivera",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} ${commissionerExtraBold.variable}
      ${plusJakartaSans.variable } ${ibmPlexSans.variable} max-w-[1440px] m-auto h-screen antialiased bg-backgroundColor`}>
        {children}
      </body>
    </html>
  );
}
